-- -- the average film length by category
-- -- include the category name and avg length
-- select name, avg(film.length) from category
-- left join film_category on category.category_id = film_category.category_id
-- left join film on film_category.film_id = film.film_id
-- where film.length is not null
-- group by category.category_id
-- order by avg(film.length) asc